### ISSUE TITLE
New C3 script modules breaks plugin

### ISSUE THREAD

**Issue by avishaymizrav** [sotano42/rex_ngio_authentication_C3_port#2]
https://www.construct.net/en/tutorials/upgrading-projects-classic-2652

**Comment by sotano42** [comment]
> https://www.construct.net/en/tutorials/upgrading-projects-classic-2652

If you can provide details on the error, how to reproduce it, and screenshots it will be appreciated.

**Comment by avishaymizrav** [comment]
> > https://www.construct.net/en/tutorials/upgrading-projects-classic-2652
> 
> If you can provide details on the error, how to reproduce it, and screenshots it will be appreciated.

Just make a new project add the plugin and try to preview (with r226+).

You'll get these error messages:

```
Uncaught ReferenceError: Newgrounds is not defined
    at f0be30bd-1101-4184-a9d9-51891f934101:1
sw.js:321 [SW-Preview] All resources saved, update ready
2aa077a1-1df8-4860-b7f7-e258f4de5b5f:15 Uncaught (in promise) TypeError: Cannot read property 'io' of undefined
    at new SingleGlobalInstance (2aa077a1-1df8-4860-b7f7-e258f4de5b5f:15)
    at Function.New (jsutil.js:9)
    at Instance._CreateSdkInstance (instance.js:7)
    at ObjectClass._CreateSingleGlobalInstance (objectClass.js:12)
    at new ObjectClass (objectClass.js:7)
    at Function.New (jsutil.js:9)
    at Function.Create (objectClass.js:7)
    at C3Runtime._LoadDataJson (runtime.js:26)
    at C3Runtime.Init (runtime.js:20)
    at async RuntimeInterface._InitDOM (domSide.js:23)
```

From what I understand globals are referenced different with modules.

**Comment by sotano42** [comment]
> > > https://www.construct.net/en/tutorials/upgrading-projects-classic-2652
> > 
> > 
> > If you can provide details on the error, how to reproduce it, and screenshots it will be appreciated.
> 
> Just make a new project add the plugin and try to preview (with r226+).
> 
> You'll get these error messages:
> 
> ```
> Uncaught ReferenceError: Newgrounds is not defined
>     at f0be30bd-1101-4184-a9d9-51891f934101:1
> sw.js:321 [SW-Preview] All resources saved, update ready
> 2aa077a1-1df8-4860-b7f7-e258f4de5b5f:15 Uncaught (in promise) TypeError: Cannot read property 'io' of undefined
>     at new SingleGlobalInstance (2aa077a1-1df8-4860-b7f7-e258f4de5b5f:15)
>     at Function.New (jsutil.js:9)
>     at Instance._CreateSdkInstance (instance.js:7)
>     at ObjectClass._CreateSingleGlobalInstance (objectClass.js:12)
>     at new ObjectClass (objectClass.js:7)
>     at Function.New (jsutil.js:9)
>     at Function.Create (objectClass.js:7)
>     at C3Runtime._LoadDataJson (runtime.js:26)
>     at C3Runtime.Init (runtime.js:20)
>     at async RuntimeInterface._InitDOM (domSide.js:23)
> ```
> 
> From what I understand globals are referenced different with modules.

This plugin does not support Worker mode, please make sure you are running your game without worker. C3 defaults worker on in the latest releases.

**Comment by avishaymizrav** [comment]
> > > > https://www.construct.net/en/tutorials/upgrading-projects-classic-2652
> > > 
> > > 
> > > If you can provide details on the error, how to reproduce it, and screenshots it will be appreciated.
> > 
> > 
> > Just make a new project add the plugin and try to preview (with r226+).
> > You'll get these error messages:
> > ```
> > Uncaught ReferenceError: Newgrounds is not defined
> >     at f0be30bd-1101-4184-a9d9-51891f934101:1
> > sw.js:321 [SW-Preview] All resources saved, update ready
> > 2aa077a1-1df8-4860-b7f7-e258f4de5b5f:15 Uncaught (in promise) TypeError: Cannot read property 'io' of undefined
> >     at new SingleGlobalInstance (2aa077a1-1df8-4860-b7f7-e258f4de5b5f:15)
> >     at Function.New (jsutil.js:9)
> >     at Instance._CreateSdkInstance (instance.js:7)
> >     at ObjectClass._CreateSingleGlobalInstance (objectClass.js:12)
> >     at new ObjectClass (objectClass.js:7)
> >     at Function.New (jsutil.js:9)
> >     at Function.Create (objectClass.js:7)
> >     at C3Runtime._LoadDataJson (runtime.js:26)
> >     at C3Runtime.Init (runtime.js:20)
> >     at async RuntimeInterface._InitDOM (domSide.js:23)
> > ```
> > 
> > 
> > From what I understand globals are referenced different with modules.
> 
> This plugin does not support Worker mode, please make sure you are running your game without worker. C3 defaults worker on in the latest releases.

Yeah sure I know, worker mode is off.

**Comment by sotano42** [comment]
The plugin works fine if you turn off the worker mode, already confirmed.

**Comment by avishaymizrav** [comment]
> The plugin works fine if you turn off the worker mode, already confirmed.

Are you sure you working on the beta branch?
This issue has nothing to do with worker mode.
I originally posted it as a bug on Scirra, since the update broke it and their official response was the plugin needs to go through some minor changes.
https://github.com/Scirra/Construct-3-bugs/issues/4377#issuecomment-734839682

**Comment by sotano42** [comment]
> > The plugin works fine if you turn off the worker mode, already confirmed.
> 
> Are you sure you working on the beta branch?
> This issue has nothing to do with worker mode.
> I originally posted it as a bug on Scirra, since the update broke it and their official response was the plugin needs to go through some minor changes.
> [Scirra/Construct-3-bugs#4377 (comment)](https://github.com/Scirra/Construct-3-bugs/issues/4377#issuecomment-734839682)

The plugin is working fine in the stable release, there's currently no support for that beta release. Please use the stable branch, when the time comes I'll try spare some time to upgrade the plugin to a new version. If it's urgent for you, you can branch it. Rex was who created the first version, I just ported it.

**Comment by sotano42** [comment]
> > The plugin works fine if you turn off the worker mode, already confirmed.
> 
> Are you sure you working on the beta branch?
> This issue has nothing to do with worker mode.
> I originally posted it as a bug on Scirra, since the update broke it and their official response was the plugin needs to go through some minor changes.
> [Scirra/Construct-3-bugs#4377 (comment)](https://github.com/Scirra/Construct-3-bugs/issues/4377#issuecomment-734839682)

One last note, make sure your scripting uses **classic mode** to support this plugin.

**Comment by avishaymizrav** [comment]
> > > The plugin works fine if you turn off the worker mode, already confirmed.
> > 
> > 
> > Are you sure you working on the beta branch?
> > This issue has nothing to do with worker mode.
> > I originally posted it as a bug on Scirra, since the update broke it and their official response was the plugin needs to go through some minor changes.
> > [Scirra/Construct-3-bugs#4377 (comment)](https://github.com/Scirra/Construct-3-bugs/issues/4377#issuecomment-734839682)
> 
> The plugin is working fine in the stable release, there's currently no support for that beta release. Please use the stable branch, when the time comes I'll try spare some time to upgrade the plugin to a new version. If it's urgent for you, you can branch it. Rex was who created the first version, I just ported it.

Sure, no problem, it's not urgent at all.
There is a temporary fix that disables the new feature in C3, but it will be removed in a few month, so I thought I'll report it asap.
Thanks for the help.
