### ISSUE TITLE
Update to modules javascript

### ISSUE THREAD

**Issue by Brin-o** [sotano42/rex_ngio_authentication_C3_port#3]
The addon currently does not work in modules mode. Since strict mode will be deprecated this addon needs to be updated.

Refer to this for more info:
https://www.construct.net/en/forum/construct-3/plugin-sdk-10/third-party-addon-changes-156802

**Comment by sotano42** [comment]
I believe the Newgrounds JS API itself is what doesn't support the modules, will see if I can do anything to fix. I don't want to modify the API.

**Comment by sotano42** [comment]
Plugin has been updated, see release notes at : https://www.construct.net/en/make-games/addons/335/newgrounds-authentication-port
